version: '3'

vars:
  PKG_PATH: ./...
  COVERAGE_OUT: coverage.out
  COVERAGE_HTML: coverage.html

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list
    silent: true

  install:
    desc: Install all dependencies
    cmds:
      - go mod download
      - go mod tidy

  build:
    desc: Build all packages
    cmds:
      - go build {{.PKG_PATH}}

  fmt:
    desc: Format code
    cmds:
      - go fmt {{.PKG_PATH}}

  vet:
    desc: Run go vet
    cmds:
      - go vet {{.PKG_PATH}}

  test:
    desc: Run tests
    cmds:
      - go test -v {{.PKG_PATH}}

  test:coverage:
    desc: Run tests with coverage (≥75% required)
    cmds:
      - go test -cover -coverprofile={{.COVERAGE_OUT}} $(go list {{.PKG_PATH}} | grep -v /examples/)
      - go tool cover -func={{.COVERAGE_OUT}}

  test:coverage:html:
    desc: Generate HTML coverage report
    deps: [test:coverage]
    cmds:
      - go tool cover -html={{.COVERAGE_OUT}} -o {{.COVERAGE_HTML}}
      - echo "Coverage report generated at {{.COVERAGE_HTML}}"

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v -race {{.PKG_PATH}}

  lint:
    desc: Run linters (if golangci-lint is installed)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run
        else
          echo "golangci-lint not installed, skipping"
        fi

  check:
    desc: Run all quality checks (fmt, vet, test)
    deps: [fmt, vet, test]
    cmds:
      - echo "✓ All checks passed"

  quality:
    desc: Run all quality checks including coverage
    deps: [fmt, vet, test:coverage]
    cmds:
      - echo "✓ All quality checks passed"

  run:example:
    desc: Run the basic example
    cmds:
      - go run examples/basic/main.go

  run:mutations:
    desc: Run the mutations example
    cmds:
      - go run examples/mutations/main.go

  clean:
    desc: Clean build artifacts and coverage files
    cmds:
      - rm -f {{.COVERAGE_OUT}} {{.COVERAGE_HTML}}
      - go clean

  tidy:
    desc: Tidy go.mod and go.sum
    cmds:
      - go mod tidy

  update:deps:
    desc: Update all dependencies
    cmds:
      - go get -u {{.PKG_PATH}}
      - go mod tidy

  doc:
    desc: Generate and serve godoc locally
    cmds:
      - |
        echo "Starting godoc server at http://localhost:6060"
        echo "View package docs at http://localhost:6060/pkg/github.com/visionik/vAgenda/api/go/"
        godoc -http=:6060

  all:
    desc: Run full local workflow (install, fmt, vet, build, test)
    cmds:
      - task install
      - task fmt
      - task vet
      - task build
      - task test
      - echo "✓ Full workflow completed successfully"
